import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsEnum,
  Length,
  Matches,
  MinLength,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
 
export enum Platform {
  ANDROID = 'ANDROID',
  IOS = 'IOS',
}

export class RegisterDeviceDto {
  @ApiProperty({
    description: 'Unique device identifier generated by the mobile application.',
    example: 'e2f9baf8-3e6a-4d0c-9a2d-8b3d67d5a123',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiPropertyOptional({
    description: 'Human-readable device name.',
    example: 'Samsung Galaxy S24',
  })
  @IsString()
  @IsOptional()
  deviceName?: string;

  @ApiPropertyOptional({
    description: 'Device operating system.',
    enum: Platform,
    example: Platform.ANDROID,
  })
  @IsEnum(Platform)
  @IsOptional()
  platform?: Platform;
}

export class SetupPinDto {
  @ApiProperty({
    description: 'Unique device identifier.',
    example: 'e2f9baf8-3e6a-4d0c-9a2d-8b3d67d5a123',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiProperty({
    description: '4 to 6 digit transaction PIN.',
    example: '1234',
    minLength: 4,
    maxLength: 6,
  })
  @IsString()
  @Length(4, 6, {
    message: 'PIN must be 4-6 digits',
  })
  pin: string;
}

export class VerifyPinDto {
  @ApiProperty({
    description: 'Unique device identifier.',
    example: 'e2f9baf8-3e6a-4d0c-9a2d-8b3d67d5a123',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiProperty({
    description: 'Previously created device PIN.',
    example: '1234',
  })
  @IsString()
  @IsNotEmpty()
  pin: string;
}

export class BiometricChallengeDto {
  @ApiProperty({
    description: 'Unique device identifier requesting a biometric challenge.',
    example: 'e2f9baf8-3e6a-4d0c-9a2d-8b3d67d5a123',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;
}

export class BiometricLoginDto {
  @ApiProperty({
    description: 'Unique device identifier.',
    example: 'e2f9baf8-3e6a-4d0c-9a2d-8b3d67d5a123',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiProperty({
    description: 'Cryptographic signature generated from the biometric challenge.',
    example: 'MEUCIQDgM2g4Q4h6xVYf2K8x3kP9xvP3kY2...',
  })
  @IsString()
  @IsNotEmpty()
  signature: string;
}

export class CheckDeviceDto {
  @ApiProperty({
    description: 'Unique device identifier.',
    example: 'e2f9baf8-3e6a-4d0c-9a2d-8b3d67d5a123',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;
}


export class ChangeDevicePasswordDto {
  @IsString()
  @IsNotEmpty()
  currentPassword: string;

  @IsString()
  @MinLength(8)
  @Matches(/^(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/, {
    message: 'Password must contain uppercase, number and symbol',
  })
  newPassword: string;
}